//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Choice.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check The Courses Offered.
        /// </summary>
        public static string checkCoursesOfferred {
            get {
                return ResourceManager.GetString("checkCoursesOfferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Check Out The.
        /// </summary>
        public static string checkOut {
            get {
                return ResourceManager.GetString("checkOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Computer Science - Mathematics, Programming.....
        /// </summary>
        public static string computerScience {
            get {
                return ResourceManager.GetString("computerScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses Offered.
        /// </summary>
        public static string coursesOffered {
            get {
                return ResourceManager.GetString("coursesOffered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Courses Suggested.
        /// </summary>
        public static string coursesSuggested {
            get {
                return ResourceManager.GetString("coursesSuggested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Electrical and Electronics - Microprocessor, Signals.....
        /// </summary>
        public static string electrical {
            get {
                return ResourceManager.GetString("electrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How It Works?.
        /// </summary>
        public static string howItWorks {
            get {
                return ResourceManager.GetString("howItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Information Technology - Data Science, Cloud Computing.....
        /// </summary>
        public static string informationTechnology {
            get {
                return ResourceManager.GetString("informationTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Jobs Eligible For.
        /// </summary>
        public static string jobsEligibile {
            get {
                return ResourceManager.GetString("jobsEligibile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to •  Select &apos;Find Your Path&apos; to Fill Out the Smart Questionnaire.
        /// </summary>
        public static string selectFindYourPath {
            get {
                return ResourceManager.GetString("selectFindYourPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Universities Offering Thouse Courses.
        /// </summary>
        public static string universitiesOffering {
            get {
                return ResourceManager.GetString("universitiesOffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Your Path.
        /// </summary>
        public static string yourPath {
            get {
                return ResourceManager.GetString("yourPath", resourceCulture);
            }
        }
    }
}
